// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package main

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RootMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsRootMessage(buf []byte, offset flatbuffers.UOffsetT) *RootMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RootMessage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRootMessage(buf []byte, offset flatbuffers.UOffsetT) *RootMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RootMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RootMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RootMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RootMessage) MType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RootMessage) MutateMType(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RootMessage) Contents(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RootMessage) ContentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RootMessage) ContentsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RootMessage) MutateContents(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func RootMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RootMessageAddMType(builder *flatbuffers.Builder, mType int32) {
	builder.PrependInt32Slot(0, mType, 0)
}
func RootMessageAddContents(builder *flatbuffers.Builder, contents flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(contents), 0)
}
func RootMessageStartContentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RootMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
